const express = require('express');
const router = express.Router();

// Importar todas las rutas
const alertasRoutes = require('./alertas');
const asistenteRoutes = require('./asistente');
const almacenRoutes = require('./almacen');
const asistenciaRoutes = require('./asistencia');
const authRoutes = require('./auth');
const backupRoutes = require('./backup');
const cajaRoutes = require('./caja');
const calculadoraRoutes = require('./calculadora');
const cotizacionesRoutes = require('./cotizaciones');
const dashboardRoutes = require('./dashboard');
const dashboardPedidosRoutes = require('./dashboardPedidos');
const dashboardUnificadoRoutes = require('./dashboardUnificado');
const etapasRoutes = require('./etapas');
const etiquetasRoutes = require('./etiquetas');
const exportacionRoutes = require('./exportacion');
const fabricacionRoutes = require('./fabricacion');
const fixRoutes = require('./fix');
const instalacionesRoutes = require('./instalaciones');
const kpisRoutes = require('./kpis');
const kpisInstalacionesRoutes = require('./kpisInstalaciones');
const metricsRoutes = require('./metrics');
const ordenCompraRoutes = require('./ordenCompraRoutes');
const pagosRoutes = require('./pagos');
const pedidosRoutes = require('./pedidos');
const pendientesRoutes = require('./pendientes');
const plantillasRoutes = require('./plantillas');
const plantillasWhatsAppRoutes = require('./plantillasWhatsApp');
const postventaRoutes = require('./postventa');
const produccionRoutes = require('./produccion');
const productosRoutes = require('./productos');
const prospectosRoutes = require('./prospectos');
const prospectosRoutesAlt = require('./prospectosRoutes');
const proyectoPedidoRoutes = require('./proyectoPedido');
const proyectosRoutes = require('./proyectos');
const recordatoriosRoutes = require('./recordatorios');
const reportesRoutes = require('./reportes');
const sobrantesRoutes = require('./sobrantes');
const storageRoutes = require('./storage');
const sugerenciasRoutes = require('./sugerencias');
const usuariosRoutes = require('./usuarios');

// Registrar rutas
router.use('/alertas', alertasRoutes);
router.use('/asistente', asistenteRoutes);
router.use('/almacen', almacenRoutes);
router.use('/asistencia', asistenciaRoutes);
router.use('/auth', authRoutes);
router.use('/backup', backupRoutes);
router.use('/caja', cajaRoutes);
router.use('/calculadora', calculadoraRoutes);
router.use('/cotizaciones', cotizacionesRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/dashboard-pedidos', dashboardPedidosRoutes);
router.use('/dashboard-unificado', dashboardUnificadoRoutes);
router.use('/etapas', etapasRoutes);
router.use('/etiquetas', etiquetasRoutes);
router.use('/exportacion', exportacionRoutes);
router.use('/fabricacion', fabricacionRoutes);
router.use('/fix', fixRoutes);
router.use('/instalaciones', instalacionesRoutes);
router.use('/kpis', kpisRoutes);
router.use('/kpis-instalaciones', kpisInstalacionesRoutes);
router.use('/metrics', metricsRoutes);
router.use('/ordenes-compra', ordenCompraRoutes);
router.use('/pagos', pagosRoutes);
router.use('/pedidos', pedidosRoutes);
router.use('/pendientes', pendientesRoutes);
router.use('/plantillas', plantillasRoutes);
router.use('/plantillas-whatsapp', plantillasWhatsAppRoutes);
router.use('/postventa', postventaRoutes);
router.use('/produccion', produccionRoutes);
router.use('/productos', productosRoutes);
router.use('/prospectos', prospectosRoutes);
router.use('/prospectos-alt', prospectosRoutesAlt);
router.use('/proyecto-pedido', proyectoPedidoRoutes);
router.use('/proyectos', proyectosRoutes);
router.use('/recordatorios', recordatoriosRoutes);
router.use('/reportes', reportesRoutes);
router.use('/sobrantes', sobrantesRoutes);
router.use('/storage', storageRoutes);
router.use('/sugerencias', sugerenciasRoutes);
router.use('/usuarios', usuariosRoutes);

module.exports = router;
